server:
  port: 8060

#for registry service. This defines where the instance of api-gateway will be stored
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#configuration of api-gateway service
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**

#for zipkin. Zipkin track the api-gateway 100%
management:
  tracing:
    sampling:
      probability: 1.0 # càd 100%

